server:
  port: 9087
spring:
 application:
    name: ADMIN-SERVICE
 datasource:
  url: jdbc:mysql://localhost:3306/telemedicine
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties: 
   hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  api-docs:
    path: /apiDocs
    